//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFC.Sample.Auditing.Services.Data
{
    using EFC.Components.Data;

    /// <summary>
    /// EmployeeData.
    /// </summary>
    public partial class EmployeeData : IEntity<int>
    {
    }
}
