//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013-07-17 - 18:04:23
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace EFC.Samples.Service.Contracts.Dto
{
    [DataContract()]
    public partial class ShopDTO
    {
        [DataMember()]
        public Int32 ShopId { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public String ShortName { get; set; }

        [DataMember()]
        public Nullable<Int32> ShopTypeId { get; set; }

        [DataMember()]
        public Nullable<Int32> ShopClassId { get; set; }

        [DataMember()]
        public Nullable<Int32> LocationId { get; set; }

        [DataMember()]
        public String Address { get; set; }

        [DataMember()]
        public Nullable<Int32> CityId { get; set; }

        [DataMember()]
        public Nullable<Int32> StateId { get; set; }

        [DataMember()]
        public Nullable<Int32> CountryId { get; set; }

        [DataMember()]
        public Nullable<Int32> ZoneId { get; set; }

        [DataMember()]
        public Nullable<Int32> RouteId { get; set; }

        [DataMember()]
        public Boolean Active { get; set; }

        [DataMember()]
        public Nullable<Int32> DistributorId { get; set; }

        [DataMember()]
        public String ContactPerson { get; set; }

        [DataMember()]
        public String ContactNo { get; set; }

        [DataMember()]
        public DateTime CreatedDate { get; set; }

        [DataMember()]
        public Nullable<DateTime> ModifiedDate { get; set; }

        [DataMember()]
        public Nullable<Int32> CreatedBy { get; set; }

        [DataMember()]
        public Nullable<Int32> DistrictId { get; set; }

        [DataMember()]
        public String MobileNo { get; set; }

        [DataMember()]
        public String Email { get; set; }

        [DataMember()]
        public String PINCode { get; set; }

        [DataMember()]
        public String TINNo { get; set; }

        [DataMember()]
        public String CSTNo { get; set; }

        [DataMember()]
        public String ThirdPartyShopCode { get; set; }

        [DataMember()]
        public Nullable<Int32> CustomerGroupId { get; set; }

        [DataMember()]
        public Nullable<Decimal> CreditLimit { get; set; }

        [DataMember()]
        public Nullable<Boolean> DailyActive { get; set; }

        [DataMember()]
        public String DoorNo { get; set; }

        [DataMember()]
        public String StreetName { get; set; }

        [DataMember()]
        public Nullable<Decimal> ShopLatitude { get; set; }

        [DataMember()]
        public Nullable<Decimal> ShopLongitude { get; set; }

        [DataMember()]
        public Nullable<Int32> TransporterId { get; set; }

        [DataMember()]
        public Nullable<Boolean> CreditStatus { get; set; }

        public ShopDTO()
        {
        }

        public ShopDTO(Int32 shopId, String name, String shortName, Nullable<Int32> shopTypeId, Nullable<Int32> shopClassId, Nullable<Int32> locationId, String address, Nullable<Int32> cityId, Nullable<Int32> stateId, Nullable<Int32> countryId, Nullable<Int32> zoneId, Nullable<Int32> routeId, Boolean active, Nullable<Int32> distributorId, String contactPerson, String contactNo, DateTime createdDate, Nullable<DateTime> modifiedDate, Nullable<Int32> createdBy, Nullable<Int32> districtId, String mobileNo, String email, String pINCode, String tINNo, String cSTNo, String thirdPartyShopCode, Nullable<Int32> customerGroupId, Nullable<Decimal> creditLimit, Nullable<Boolean> dailyActive, String doorNo, String streetName, Nullable<Decimal> shopLatitude, Nullable<Decimal> shopLongitude, Nullable<Int32> transporterId, Nullable<Boolean> creditStatus)
        {
			this.ShopId = shopId;
			this.Name = name;
			this.ShortName = shortName;
			this.ShopTypeId = shopTypeId;
			this.ShopClassId = shopClassId;
			this.LocationId = locationId;
			this.Address = address;
			this.CityId = cityId;
			this.StateId = stateId;
			this.CountryId = countryId;
			this.ZoneId = zoneId;
			this.RouteId = routeId;
			this.Active = active;
			this.DistributorId = distributorId;
			this.ContactPerson = contactPerson;
			this.ContactNo = contactNo;
			this.CreatedDate = createdDate;
			this.ModifiedDate = modifiedDate;
			this.CreatedBy = createdBy;
			this.DistrictId = districtId;
			this.MobileNo = mobileNo;
			this.Email = email;
			this.PINCode = pINCode;
			this.TINNo = tINNo;
			this.CSTNo = cSTNo;
			this.ThirdPartyShopCode = thirdPartyShopCode;
			this.CustomerGroupId = customerGroupId;
			this.CreditLimit = creditLimit;
			this.DailyActive = dailyActive;
			this.DoorNo = doorNo;
			this.StreetName = streetName;
			this.ShopLatitude = shopLatitude;
			this.ShopLongitude = shopLongitude;
			this.TransporterId = transporterId;
			this.CreditStatus = creditStatus;
        }
    }
}
