//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-05 - 16.15.31
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using EFC.Sample.Auditing.Data.Contracts.Dto;
using EFC.Sample.Auditing.Services.Data;

namespace EFC.Sample.Auditing.Services.Extensions
{

    /// <summary>
    /// Assembler for <see cref="EmployeeData"/> and <see cref="EmployeeDataDto"/>.
    /// </summary>
    public static partial class EmployeeDataExtensions
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="EmployeeDataDto"/> converted from <see cref="EmployeeData"/>.</param>
        static partial void OnDTO(this EmployeeData entity, EmployeeDataDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="EmployeeData"/> converted from <see cref="EmployeeDataDto"/>.</param>
        static partial void OnEntity(this EmployeeDataDto dto, EmployeeData entity);

        /// <summary>
        /// Converts this instance of <see cref="EmployeeDataDto"/> to an instance of <see cref="EmployeeData"/>.
        /// </summary>
        /// <param name="dto"><see cref="EmployeeDataDto"/> to convert.</param>
        public static EmployeeData ToEntity(this EmployeeDataDto dto)
        {
            if (dto == null) return null;

            var entity = new EmployeeData();

            entity.Id = dto.Id;
            entity.FirstName = dto.FirstName;
            entity.LastName = dto.LastName;
            entity.DOB = dto.DOB;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="EmployeeData"/> to an instance of <see cref="EmployeeDataDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="EmployeeData"/> to convert.</param>
        public static EmployeeDataDto ToDTO(this EmployeeData entity)
        {
            if (entity == null) return null;

            var dto = new EmployeeDataDto();

            dto.Id = entity.Id;
            dto.FirstName = entity.FirstName;
            dto.LastName = entity.LastName;
            dto.DOB = entity.DOB;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="EmployeeDataDto"/> to an instance of <see cref="EmployeeData"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<EmployeeData> ToEntities(this IEnumerable<EmployeeDataDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="EmployeeData"/> to an instance of <see cref="EmployeeDataDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<EmployeeDataDto> ToDTOs(this IEnumerable<EmployeeData> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
