//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-05 - 16.15.31
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using EFC.Sample.Auditing.Data.Contracts.Dto;
using EFC.Sample.Auditing.Services.Data;

namespace EFC.Sample.Auditing.Services.Extensions
{

    /// <summary>
    /// Assembler for <see cref="EmployeeDepartmentMapping"/> and <see cref="EmployeeDepartmentMappingDto"/>.
    /// </summary>
    public static partial class EmployeeDepartmentMappingExtensions
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="EmployeeDepartmentMappingDto"/> converted from <see cref="EmployeeDepartmentMapping"/>.</param>
        static partial void OnDTO(this EmployeeDepartmentMapping entity, EmployeeDepartmentMappingDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="EmployeeDepartmentMapping"/> converted from <see cref="EmployeeDepartmentMappingDto"/>.</param>
        static partial void OnEntity(this EmployeeDepartmentMappingDto dto, EmployeeDepartmentMapping entity);

        /// <summary>
        /// Converts this instance of <see cref="EmployeeDepartmentMappingDto"/> to an instance of <see cref="EmployeeDepartmentMapping"/>.
        /// </summary>
        /// <param name="dto"><see cref="EmployeeDepartmentMappingDto"/> to convert.</param>
        public static EmployeeDepartmentMapping ToEntity(this EmployeeDepartmentMappingDto dto)
        {
            if (dto == null) return null;

            var entity = new EmployeeDepartmentMapping();

            entity.Id = dto.Id;
            entity.DepartmentId = dto.DepartmentId;
            entity.EmployeeId = dto.EmployeeId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="EmployeeDepartmentMapping"/> to an instance of <see cref="EmployeeDepartmentMappingDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="EmployeeDepartmentMapping"/> to convert.</param>
        public static EmployeeDepartmentMappingDto ToDTO(this EmployeeDepartmentMapping entity)
        {
            if (entity == null) return null;

            var dto = new EmployeeDepartmentMappingDto();

            dto.Id = entity.Id;
            dto.DepartmentId = entity.DepartmentId;
            dto.EmployeeId = entity.EmployeeId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="EmployeeDepartmentMappingDto"/> to an instance of <see cref="EmployeeDepartmentMapping"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<EmployeeDepartmentMapping> ToEntities(this IEnumerable<EmployeeDepartmentMappingDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="EmployeeDepartmentMapping"/> to an instance of <see cref="EmployeeDepartmentMappingDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<EmployeeDepartmentMappingDto> ToDTOs(this IEnumerable<EmployeeDepartmentMapping> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
