//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTsys.PMOService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceLogDto", Namespace="http://schemas.datacontract.org/2004/07/Experion.PMO.Data.Contracts")]
    [System.SerializableAttribute()]
    public partial class DeviceLogDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttDirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DeviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DeviceLogIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DownloadDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TTsys.PMOService.EmployeeDto EmployeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LogDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttDirection {
            get {
                return this.AttDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.AttDirectionField, value) != true)) {
                    this.AttDirectionField = value;
                    this.RaisePropertyChanged("AttDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C1 {
            get {
                return this.C1Field;
            }
            set {
                if ((object.ReferenceEquals(this.C1Field, value) != true)) {
                    this.C1Field = value;
                    this.RaisePropertyChanged("C1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C2 {
            get {
                return this.C2Field;
            }
            set {
                if ((object.ReferenceEquals(this.C2Field, value) != true)) {
                    this.C2Field = value;
                    this.RaisePropertyChanged("C2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C3 {
            get {
                return this.C3Field;
            }
            set {
                if ((object.ReferenceEquals(this.C3Field, value) != true)) {
                    this.C3Field = value;
                    this.RaisePropertyChanged("C3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C4 {
            get {
                return this.C4Field;
            }
            set {
                if ((object.ReferenceEquals(this.C4Field, value) != true)) {
                    this.C4Field = value;
                    this.RaisePropertyChanged("C4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C5 {
            get {
                return this.C5Field;
            }
            set {
                if ((object.ReferenceEquals(this.C5Field, value) != true)) {
                    this.C5Field = value;
                    this.RaisePropertyChanged("C5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C6 {
            get {
                return this.C6Field;
            }
            set {
                if ((object.ReferenceEquals(this.C6Field, value) != true)) {
                    this.C6Field = value;
                    this.RaisePropertyChanged("C6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C7 {
            get {
                return this.C7Field;
            }
            set {
                if ((object.ReferenceEquals(this.C7Field, value) != true)) {
                    this.C7Field = value;
                    this.RaisePropertyChanged("C7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeviceId {
            get {
                return this.DeviceIdField;
            }
            set {
                if ((this.DeviceIdField.Equals(value) != true)) {
                    this.DeviceIdField = value;
                    this.RaisePropertyChanged("DeviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeviceLogId {
            get {
                return this.DeviceLogIdField;
            }
            set {
                if ((this.DeviceLogIdField.Equals(value) != true)) {
                    this.DeviceLogIdField = value;
                    this.RaisePropertyChanged("DeviceLogId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direction {
            get {
                return this.DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectionField, value) != true)) {
                    this.DirectionField = value;
                    this.RaisePropertyChanged("Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DownloadDate {
            get {
                return this.DownloadDateField;
            }
            set {
                if ((this.DownloadDateField.Equals(value) != true)) {
                    this.DownloadDateField = value;
                    this.RaisePropertyChanged("DownloadDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TTsys.PMOService.EmployeeDto Employee {
            get {
                return this.EmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeField, value) != true)) {
                    this.EmployeeField = value;
                    this.RaisePropertyChanged("Employee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LogDate {
            get {
                return this.LogDateField;
            }
            set {
                if ((this.LogDateField.Equals(value) != true)) {
                    this.LogDateField = value;
                    this.RaisePropertyChanged("LogDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkCode {
            get {
                return this.WorkCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkCodeField, value) != true)) {
                    this.WorkCodeField = value;
                    this.RaisePropertyChanged("WorkCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeDto", Namespace="http://schemas.datacontract.org/2004/07/Experion.PMO.Data.Contracts")]
    [System.SerializableAttribute()]
    public partial class EmployeeDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BLOODGROUPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DOCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DOJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TTsys.PMOService.DeviceLogDto[] DeviceLogsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeCodeInDeviceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeDeviceGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeDevicePasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeRFIDNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployementTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FatherNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HolidayGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IsRecieveNotificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotherNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nomenee1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nomenee2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumericCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PermanentAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RecordStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResidentialAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ShiftGroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ShiftRosterIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkPlaceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BLOODGROUP {
            get {
                return this.BLOODGROUPField;
            }
            set {
                if ((object.ReferenceEquals(this.BLOODGROUPField, value) != true)) {
                    this.BLOODGROUPField = value;
                    this.RaisePropertyChanged("BLOODGROUP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C1 {
            get {
                return this.C1Field;
            }
            set {
                if ((object.ReferenceEquals(this.C1Field, value) != true)) {
                    this.C1Field = value;
                    this.RaisePropertyChanged("C1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C2 {
            get {
                return this.C2Field;
            }
            set {
                if ((object.ReferenceEquals(this.C2Field, value) != true)) {
                    this.C2Field = value;
                    this.RaisePropertyChanged("C2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C3 {
            get {
                return this.C3Field;
            }
            set {
                if ((object.ReferenceEquals(this.C3Field, value) != true)) {
                    this.C3Field = value;
                    this.RaisePropertyChanged("C3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C4 {
            get {
                return this.C4Field;
            }
            set {
                if ((object.ReferenceEquals(this.C4Field, value) != true)) {
                    this.C4Field = value;
                    this.RaisePropertyChanged("C4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C5 {
            get {
                return this.C5Field;
            }
            set {
                if ((object.ReferenceEquals(this.C5Field, value) != true)) {
                    this.C5Field = value;
                    this.RaisePropertyChanged("C5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C6 {
            get {
                return this.C6Field;
            }
            set {
                if ((object.ReferenceEquals(this.C6Field, value) != true)) {
                    this.C6Field = value;
                    this.RaisePropertyChanged("C6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C7 {
            get {
                return this.C7Field;
            }
            set {
                if ((object.ReferenceEquals(this.C7Field, value) != true)) {
                    this.C7Field = value;
                    this.RaisePropertyChanged("C7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactNo {
            get {
                return this.ContactNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNoField, value) != true)) {
                    this.ContactNoField = value;
                    this.RaisePropertyChanged("ContactNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((this.DOBField.Equals(value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DOC {
            get {
                return this.DOCField;
            }
            set {
                if ((this.DOCField.Equals(value) != true)) {
                    this.DOCField = value;
                    this.RaisePropertyChanged("DOC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DOJ {
            get {
                return this.DOJField;
            }
            set {
                if ((this.DOJField.Equals(value) != true)) {
                    this.DOJField = value;
                    this.RaisePropertyChanged("DOJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DOR {
            get {
                return this.DORField;
            }
            set {
                if ((this.DORField.Equals(value) != true)) {
                    this.DORField = value;
                    this.RaisePropertyChanged("DOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentId {
            get {
                return this.DepartmentIdField;
            }
            set {
                if ((this.DepartmentIdField.Equals(value) != true)) {
                    this.DepartmentIdField = value;
                    this.RaisePropertyChanged("DepartmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Designation {
            get {
                return this.DesignationField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignationField, value) != true)) {
                    this.DesignationField = value;
                    this.RaisePropertyChanged("Designation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TTsys.PMOService.DeviceLogDto[] DeviceLogs {
            get {
                return this.DeviceLogsField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceLogsField, value) != true)) {
                    this.DeviceLogsField = value;
                    this.RaisePropertyChanged("DeviceLogs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeCode {
            get {
                return this.EmployeeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeCodeField, value) != true)) {
                    this.EmployeeCodeField = value;
                    this.RaisePropertyChanged("EmployeeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeCodeInDevice {
            get {
                return this.EmployeeCodeInDeviceField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeCodeInDeviceField, value) != true)) {
                    this.EmployeeCodeInDeviceField = value;
                    this.RaisePropertyChanged("EmployeeCodeInDevice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeDeviceGroup {
            get {
                return this.EmployeeDeviceGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeDeviceGroupField, value) != true)) {
                    this.EmployeeDeviceGroupField = value;
                    this.RaisePropertyChanged("EmployeeDeviceGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeDevicePassword {
            get {
                return this.EmployeeDevicePasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeDevicePasswordField, value) != true)) {
                    this.EmployeeDevicePasswordField = value;
                    this.RaisePropertyChanged("EmployeeDevicePassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((this.EmployeeIdField.Equals(value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeName {
            get {
                return this.EmployeeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNameField, value) != true)) {
                    this.EmployeeNameField = value;
                    this.RaisePropertyChanged("EmployeeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeRFIDNumber {
            get {
                return this.EmployeeRFIDNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeRFIDNumberField, value) != true)) {
                    this.EmployeeRFIDNumberField = value;
                    this.RaisePropertyChanged("EmployeeRFIDNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployementType {
            get {
                return this.EmployementTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployementTypeField, value) != true)) {
                    this.EmployementTypeField = value;
                    this.RaisePropertyChanged("EmployementType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtensionNo {
            get {
                return this.ExtensionNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionNoField, value) != true)) {
                    this.ExtensionNoField = value;
                    this.RaisePropertyChanged("ExtensionNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FatherName {
            get {
                return this.FatherNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FatherNameField, value) != true)) {
                    this.FatherNameField = value;
                    this.RaisePropertyChanged("FatherName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grade {
            get {
                return this.GradeField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeField, value) != true)) {
                    this.GradeField = value;
                    this.RaisePropertyChanged("Grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HolidayGroup {
            get {
                return this.HolidayGroupField;
            }
            set {
                if ((this.HolidayGroupField.Equals(value) != true)) {
                    this.HolidayGroupField = value;
                    this.RaisePropertyChanged("HolidayGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IsRecieveNotification {
            get {
                return this.IsRecieveNotificationField;
            }
            set {
                if ((this.IsRecieveNotificationField.Equals(value) != true)) {
                    this.IsRecieveNotificationField = value;
                    this.RaisePropertyChanged("IsRecieveNotification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastModifiedBy {
            get {
                return this.LastModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.LastModifiedByField, value) != true)) {
                    this.LastModifiedByField = value;
                    this.RaisePropertyChanged("LastModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginName {
            get {
                return this.LoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginNameField, value) != true)) {
                    this.LoginNameField = value;
                    this.RaisePropertyChanged("LoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginPassword {
            get {
                return this.LoginPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginPasswordField, value) != true)) {
                    this.LoginPasswordField = value;
                    this.RaisePropertyChanged("LoginPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotherName {
            get {
                return this.MotherNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MotherNameField, value) != true)) {
                    this.MotherNameField = value;
                    this.RaisePropertyChanged("MotherName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nomenee1 {
            get {
                return this.Nomenee1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Nomenee1Field, value) != true)) {
                    this.Nomenee1Field = value;
                    this.RaisePropertyChanged("Nomenee1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nomenee2 {
            get {
                return this.Nomenee2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Nomenee2Field, value) != true)) {
                    this.Nomenee2Field = value;
                    this.RaisePropertyChanged("Nomenee2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumericCode {
            get {
                return this.NumericCodeField;
            }
            set {
                if ((this.NumericCodeField.Equals(value) != true)) {
                    this.NumericCodeField = value;
                    this.RaisePropertyChanged("NumericCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PermanentAddress {
            get {
                return this.PermanentAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.PermanentAddressField, value) != true)) {
                    this.PermanentAddressField = value;
                    this.RaisePropertyChanged("PermanentAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlaceOfBirth {
            get {
                return this.PlaceOfBirthField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceOfBirthField, value) != true)) {
                    this.PlaceOfBirthField = value;
                    this.RaisePropertyChanged("PlaceOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RecordStatus {
            get {
                return this.RecordStatusField;
            }
            set {
                if ((this.RecordStatusField.Equals(value) != true)) {
                    this.RecordStatusField = value;
                    this.RaisePropertyChanged("RecordStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks {
            get {
                return this.RemarksField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarksField, value) != true)) {
                    this.RemarksField = value;
                    this.RaisePropertyChanged("Remarks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResidentialAddress {
            get {
                return this.ResidentialAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ResidentialAddressField, value) != true)) {
                    this.ResidentialAddressField = value;
                    this.RaisePropertyChanged("ResidentialAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ShiftGroupId {
            get {
                return this.ShiftGroupIdField;
            }
            set {
                if ((this.ShiftGroupIdField.Equals(value) != true)) {
                    this.ShiftGroupIdField = value;
                    this.RaisePropertyChanged("ShiftGroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ShiftRosterId {
            get {
                return this.ShiftRosterIdField;
            }
            set {
                if ((this.ShiftRosterIdField.Equals(value) != true)) {
                    this.ShiftRosterIdField = value;
                    this.RaisePropertyChanged("ShiftRosterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringCode {
            get {
                return this.StringCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StringCodeField, value) != true)) {
                    this.StringCodeField = value;
                    this.RaisePropertyChanged("StringCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Team {
            get {
                return this.TeamField;
            }
            set {
                if ((object.ReferenceEquals(this.TeamField, value) != true)) {
                    this.TeamField = value;
                    this.RaisePropertyChanged("Team");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkPlace {
            get {
                return this.WorkPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkPlaceField, value) != true)) {
                    this.WorkPlaceField = value;
                    this.RaisePropertyChanged("WorkPlace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogEntryDto", Namespace="http://schemas.datacontract.org/2004/07/Experion.PMO.Data.Contracts")]
    [System.SerializableAttribute()]
    public partial class LogEntryDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EffortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direction {
            get {
                return this.DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectionField, value) != true)) {
                    this.DirectionField = value;
                    this.RaisePropertyChanged("Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Effort {
            get {
                return this.EffortField;
            }
            set {
                if ((this.EffortField.Equals(value) != true)) {
                    this.EffortField = value;
                    this.RaisePropertyChanged("Effort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIdField, value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeLeaveDto", Namespace="http://schemas.datacontract.org/2004/07/Experion.PMO.Data.Contracts")]
    [System.SerializableAttribute()]
    public partial class EmployeeLeaveDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EffortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LeaveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Effort {
            get {
                return this.EffortField;
            }
            set {
                if ((this.EffortField.Equals(value) != true)) {
                    this.EffortField = value;
                    this.RaisePropertyChanged("Effort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeId {
            get {
                return this.EmployeeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIdField, value) != true)) {
                    this.EmployeeIdField = value;
                    this.RaisePropertyChanged("EmployeeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeName {
            get {
                return this.EmployeeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNameField, value) != true)) {
                    this.EmployeeNameField = value;
                    this.RaisePropertyChanged("EmployeeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Leave {
            get {
                return this.LeaveField;
            }
            set {
                if ((this.LeaveField.Equals(value) != true)) {
                    this.LeaveField = value;
                    this.RaisePropertyChanged("Leave");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PMOService.IPMOService")]
    public interface IPMOService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMOService/GetData", ReplyAction="http://tempuri.org/IPMOService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMOService/GetData", ReplyAction="http://tempuri.org/IPMOService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMOService/GetAllDeviceLogs", ReplyAction="http://tempuri.org/IPMOService/GetAllDeviceLogsResponse")]
        TTsys.PMOService.DeviceLogDto[] GetAllDeviceLogs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMOService/GetAllDeviceLogs", ReplyAction="http://tempuri.org/IPMOService/GetAllDeviceLogsResponse")]
        System.Threading.Tasks.Task<TTsys.PMOService.DeviceLogDto[]> GetAllDeviceLogsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMOService/GetEffort", ReplyAction="http://tempuri.org/IPMOService/GetEffortResponse")]
        double GetEffort(System.DateTime dateFrom, int empoyeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMOService/GetEffort", ReplyAction="http://tempuri.org/IPMOService/GetEffortResponse")]
        System.Threading.Tasks.Task<double> GetEffortAsync(System.DateTime dateFrom, int empoyeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMOService/GetLogTransacion", ReplyAction="http://tempuri.org/IPMOService/GetLogTransacionResponse")]
        System.Collections.Generic.Dictionary<System.DateTime, TTsys.PMOService.LogEntryDto[]> GetLogTransacion(System.DateTime dateFrom, System.DateTime dateTo, int employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMOService/GetLogTransacion", ReplyAction="http://tempuri.org/IPMOService/GetLogTransacionResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<System.DateTime, TTsys.PMOService.LogEntryDto[]>> GetLogTransacionAsync(System.DateTime dateFrom, System.DateTime dateTo, int employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMOService/GetPossibleLeaveEntry", ReplyAction="http://tempuri.org/IPMOService/GetPossibleLeaveEntryResponse")]
        System.Collections.Generic.Dictionary<string, TTsys.PMOService.EmployeeLeaveDto> GetPossibleLeaveEntry(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMOService/GetPossibleLeaveEntry", ReplyAction="http://tempuri.org/IPMOService/GetPossibleLeaveEntryResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, TTsys.PMOService.EmployeeLeaveDto>> GetPossibleLeaveEntryAsync(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMOService/AddLogEntry", ReplyAction="http://tempuri.org/IPMOService/AddLogEntryResponse")]
        bool AddLogEntry(TTsys.PMOService.DeviceLogDto log);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPMOService/AddLogEntry", ReplyAction="http://tempuri.org/IPMOService/AddLogEntryResponse")]
        System.Threading.Tasks.Task<bool> AddLogEntryAsync(TTsys.PMOService.DeviceLogDto log);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPMOServiceChannel : TTsys.PMOService.IPMOService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PMOServiceClient : System.ServiceModel.ClientBase<TTsys.PMOService.IPMOService>, TTsys.PMOService.IPMOService {
        
        public PMOServiceClient() {
        }
        
        public PMOServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PMOServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PMOServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PMOServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public TTsys.PMOService.DeviceLogDto[] GetAllDeviceLogs() {
            return base.Channel.GetAllDeviceLogs();
        }
        
        public System.Threading.Tasks.Task<TTsys.PMOService.DeviceLogDto[]> GetAllDeviceLogsAsync() {
            return base.Channel.GetAllDeviceLogsAsync();
        }
        
        public double GetEffort(System.DateTime dateFrom, int empoyeeID) {
            return base.Channel.GetEffort(dateFrom, empoyeeID);
        }
        
        public System.Threading.Tasks.Task<double> GetEffortAsync(System.DateTime dateFrom, int empoyeeID) {
            return base.Channel.GetEffortAsync(dateFrom, empoyeeID);
        }
        
        public System.Collections.Generic.Dictionary<System.DateTime, TTsys.PMOService.LogEntryDto[]> GetLogTransacion(System.DateTime dateFrom, System.DateTime dateTo, int employeeId) {
            return base.Channel.GetLogTransacion(dateFrom, dateTo, employeeId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<System.DateTime, TTsys.PMOService.LogEntryDto[]>> GetLogTransacionAsync(System.DateTime dateFrom, System.DateTime dateTo, int employeeId) {
            return base.Channel.GetLogTransacionAsync(dateFrom, dateTo, employeeId);
        }
        
        public System.Collections.Generic.Dictionary<string, TTsys.PMOService.EmployeeLeaveDto> GetPossibleLeaveEntry(System.DateTime date) {
            return base.Channel.GetPossibleLeaveEntry(date);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, TTsys.PMOService.EmployeeLeaveDto>> GetPossibleLeaveEntryAsync(System.DateTime date) {
            return base.Channel.GetPossibleLeaveEntryAsync(date);
        }
        
        public bool AddLogEntry(TTsys.PMOService.DeviceLogDto log) {
            return base.Channel.AddLogEntry(log);
        }
        
        public System.Threading.Tasks.Task<bool> AddLogEntryAsync(TTsys.PMOService.DeviceLogDto log) {
            return base.Channel.AddLogEntryAsync(log);
        }
    }
}
