//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013-07-17 - 13:27:03
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using EFC.Samples.Service.Model;

namespace EFC.Samples.Service.Contracts.Dto
{

    /// <summary>
    /// Assembler for <see cref="SalesDetail"/> and <see cref="SalesDetailDTO"/>.
    /// </summary>
    public static partial class SalesDetailAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="SalesDetailDTO"/> converted from <see cref="SalesDetail"/>.</param>
        static partial void OnDTO(this SalesDetail entity, SalesDetailDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="SalesDetail"/> converted from <see cref="SalesDetailDTO"/>.</param>
        static partial void OnEntity(this SalesDetailDTO dto, SalesDetail entity);

        /// <summary>
        /// Converts this instance of <see cref="SalesDetailDTO"/> to an instance of <see cref="SalesDetail"/>.
        /// </summary>
        /// <param name="dto"><see cref="SalesDetailDTO"/> to convert.</param>
        public static SalesDetail ToEntity(this SalesDetailDTO dto)
        {
            if (dto == null) return null;

            var entity = new SalesDetail();

            entity.SalesDetailsId = dto.SalesDetailsId;
            entity.InvoiceDate = dto.InvoiceDate;
            entity.InvoiceNo = dto.InvoiceNo;
            entity.ShopId = dto.ShopId;
            entity.ProductAttributeId = dto.ProductAttributeId;
            entity.Quantity = dto.Quantity;
            entity.Amount = dto.Amount;
            entity.UserId = dto.UserId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="SalesDetail"/> to an instance of <see cref="SalesDetailDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="SalesDetail"/> to convert.</param>
        public static SalesDetailDTO ToDTO(this SalesDetail entity)
        {
            if (entity == null) return null;

            var dto = new SalesDetailDTO();

            dto.SalesDetailsId = entity.SalesDetailsId;
            dto.InvoiceDate = entity.InvoiceDate;
            dto.InvoiceNo = entity.InvoiceNo;
            dto.ShopId = entity.ShopId;
            dto.ProductAttributeId = entity.ProductAttributeId;
            dto.Quantity = entity.Quantity;
            dto.Amount = entity.Amount;
            dto.UserId = entity.UserId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="SalesDetailDTO"/> to an instance of <see cref="SalesDetail"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<SalesDetail> ToEntities(this IEnumerable<SalesDetailDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="SalesDetail"/> to an instance of <see cref="SalesDetailDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<SalesDetailDTO> ToDTOs(this IEnumerable<SalesDetail> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
