//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFC.Samples.Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeatPlanSetting
    {
        public int SettingId { get; set; }
        public int BeatPlanId { get; set; }
        public int ShopId { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual BeatPlan BeatPlan { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
