//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFC.Samples.Service.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FieldMaxDataContainer : DbContext
    {
        public FieldMaxDataContainer()
            : base("name=FieldMaxDataContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BeatPlan> BeatPlans { get; set; }
        public DbSet<BeatPlanSetting> BeatPlanSettings { get; set; }
        public DbSet<SalesDetail> SalesDetails { get; set; }
        public DbSet<Shop> Shops { get; set; }
        public DbSet<ActiveShop> ActiveShops { get; set; }
    }
}
