//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFC.Samples.Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public Shop()
        {
            this.BeatPlanSettings = new HashSet<BeatPlanSetting>();
        }
    
        public int ShopId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> ShopTypeId { get; set; }
        public Nullable<int> ShopClassId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Address { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public Nullable<int> RouteId { get; set; }
        public bool Active { get; set; }
        public Nullable<int> DistributorId { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string PINCode { get; set; }
        public string TINNo { get; set; }
        public string CSTNo { get; set; }
        public string ThirdPartyShopCode { get; set; }
        public Nullable<int> CustomerGroupId { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<bool> DailyActive { get; set; }
        public string DoorNo { get; set; }
        public string StreetName { get; set; }
        public Nullable<decimal> ShopLatitude { get; set; }
        public Nullable<decimal> ShopLongitude { get; set; }
        public Nullable<int> TransporterId { get; set; }
        public Nullable<bool> CreditStatus { get; set; }
    
        public virtual ICollection<BeatPlanSetting> BeatPlanSettings { get; set; }
    }
}
