//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFC.Components {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFC.Components.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials with key {0} already exists..
        /// </summary>
        internal static string AlreadyExistingCredentials {
            get {
                return ResourceManager.GetString("AlreadyExistingCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must contain at least one element..
        /// </summary>
        internal static string ArgumentEmptyCollection {
            get {
                return ResourceManager.GetString("ArgumentEmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be empty..
        /// </summary>
        internal static string ArgumentEmptyString {
            get {
                return ResourceManager.GetString("ArgumentEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is not an interface type..
        /// </summary>
        internal static string ArgumentNotAnInterface {
            get {
                return ResourceManager.GetString("ArgumentNotAnInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not assignable from &apos;{1}&apos;..
        /// </summary>
        internal static string ArgumentNotAssignable {
            get {
                return ResourceManager.GetString("ArgumentNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is not of the expected type &apos;{0}&apos;..
        /// </summary>
        internal static string ArgumentNotExpectedType {
            get {
                return ResourceManager.GetString("ArgumentNotExpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot contain a null element..
        /// </summary>
        internal static string ArgumentNullElement {
            get {
                return ResourceManager.GetString("ArgumentNullElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async object already completed..
        /// </summary>
        internal static string AsyncCompleted {
            get {
                return ResourceManager.GetString("AsyncCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async object already ended..
        /// </summary>
        internal static string AsyncEnded {
            get {
                return ResourceManager.GetString("AsyncEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; member cannot be called more than one time..
        /// </summary>
        internal static string CalledTwice {
            get {
                return ResourceManager.GetString("CalledTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access a expired data..
        /// </summary>
        internal static string DataExpired {
            get {
                return ResourceManager.GetString("DataExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultLoggingConfiguration.
        /// </summary>
        internal static string DefaultLoggingConfiguration {
            get {
                return ResourceManager.GetString("DefaultLoggingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string DefaultLogSource {
            get {
                return ResourceManager.GetString("DefaultLogSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default value of parameter &apos;{0}&apos; can not be converted to the parameter of type &apos;{1}&apos;. Please check if the value is appropriate to the parameter type or if the parameter type is a primitive type (Only primitive types are supported)..
        /// </summary>
        internal static string DefaultValueCanNotBeConverted {
            get {
                return ResourceManager.GetString("DefaultValueCanNotBeConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default value of parameter &apos;{0}&apos; can not be converted to the parameter of type &apos;{1}&apos;. Please check if the value is appropriate to the parameter type or if the parameter type is a primitive type (Only primitive types are supported)..
        /// </summary>
        internal static string DefaultValueCanNotBeConverted1 {
            get {
                return ResourceManager.GetString("DefaultValueCanNotBeConverted1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory &apos;{0}&apos; was not found..
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The publication was already registered.
        /// </summary>
        internal static string DuplicatedPublication {
            get {
                return ResourceManager.GetString("DuplicatedPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-zA-Z][\w\.-]*[a-zA-Z0-9]@[a-zA-Z0-9][\w\.-]*[a-zA-Z0-9]\.[a-zA-Z][a-zA-Z\.]*[a-zA-Z]$.
        /// </summary>
        internal static string EmailFormatValidation {
            get {
                return ResourceManager.GetString("EmailFormatValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter in configuration is empty..
        /// </summary>
        internal static string EmptyConfigurationParameter {
            get {
                return ResourceManager.GetString("EmptyConfigurationParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method entry point has been reached..
        /// </summary>
        internal static string Entry {
            get {
                return ResourceManager.GetString("Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred..
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published EventArgs of type &apos;{0}&apos; are not assignable to subscriber handler method EventArgs paramter of type &apos;{1}&apos;.
        /// </summary>
        internal static string EventArgsAreNotAssignable {
            get {
                return ResourceManager.GetString("EventArgsAreNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event with name &apos;{0}&apos; is not a public member of defined publisher type &apos;{1}&apos;..
        /// </summary>
        internal static string EventNotFound {
            get {
                return ResourceManager.GetString("EventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception handling within exception policy: {0}.
        /// </summary>
        internal static string ExceptionLoggingMessage {
            get {
                return ResourceManager.GetString("ExceptionLoggingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExceptionPolicy.
        /// </summary>
        internal static string ExceptionPolicyLoggingCategoryName {
            get {
                return ResourceManager.GetString("ExceptionPolicyLoggingCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No extension points found that match specified contract name and type.
        /// </summary>
        internal static string ExtensionPointCardinalityMismatch_NoExports {
            get {
                return ResourceManager.GetString("ExtensionPointCardinalityMismatch_NoExports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error in performance logging component..
        /// </summary>
        internal static string FatalErrorPerformanceLogging {
            get {
                return ResourceManager.GetString("FatalErrorPerformanceLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; was not found..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not read input stream..
        /// </summary>
        internal static string FtpCanNotReadStream {
            get {
                return ResourceManager.GetString("FtpCanNotReadStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sending of file failed..
        /// </summary>
        internal static string FtpFileSendingFailed {
            get {
                return ResourceManager.GetString("FtpFileSendingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value is not supported as an argument for this API..
        /// </summary>
        internal static string InvalidArgumentValue {
            get {
                return ResourceManager.GetString("InvalidArgumentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters of the handler method are not valid for event handler.
        /// </summary>
        internal static string InvalidEventHandlerParameters {
            get {
                return ResourceManager.GetString("InvalidEventHandlerParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception policy is not able to compute proper return value..
        /// </summary>
        internal static string InvalidOperationException {
            get {
                return ResourceManager.GetString("InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter set used for resource mapping in configuration file. Try {{key, type}} or {{key, baseName, resourceDir}} or {{key, baseName, assembly}}..
        /// </summary>
        internal static string InvalidParameterSetForMapping {
            get {
                return ResourceManager.GetString("InvalidParameterSetForMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property name is invalid..
        /// </summary>
        internal static string InvalidPropertyName {
            get {
                return ResourceManager.GetString("InvalidPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key &apos;{0}&apos; was not found..
        /// </summary>
        internal static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast one category should be defined under a logging configuration..
        /// </summary>
        internal static string LogSourceCategoryError {
            get {
                return ResourceManager.GetString("LogSourceCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message is not applicable for that kind of notifier..
        /// </summary>
        internal static string MessageNotApplicable {
            get {
                return ResourceManager.GetString("MessageNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authenticated..
        /// </summary>
        internal static string NotAuthenticated {
            get {
                return ResourceManager.GetString("NotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorized..
        /// </summary>
        internal static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; member must be overridden by a derived class..
        /// </summary>
        internal static string NotOverridden {
            get {
                return ResourceManager.GetString("NotOverridden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access a uninitialized object..
        /// </summary>
        internal static string ObjectUninitialized {
            get {
                return ResourceManager.GetString("ObjectUninitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event with name &apos;{0}&apos; could not be registered as a publication. The event is not a valid event handler with signature: void(object, EventArgs)..
        /// </summary>
        internal static string OnlyEventHandlerSignaturesAreSupported {
            get {
                return ResourceManager.GetString("OnlyEventHandlerSignaturesAreSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event handler method passed as a parameter cannot be static..
        /// </summary>
        internal static string PassedMethodCantBeStatic {
            get {
                return ResourceManager.GetString("PassedMethodCantBeStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event handler method passed as a parameter must be static..
        /// </summary>
        internal static string PassedMethodMustBeStatic {
            get {
                return ResourceManager.GetString("PassedMethodMustBeStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy &apos;{0}&apos; arleady exists in policy container..
        /// </summary>
        internal static string PolicyDuplicationExceptionMessage {
            get {
                return ResourceManager.GetString("PolicyDuplicationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy &apos;{0}&apos; not found in policy container..
        /// </summary>
        internal static string PolicyNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("PolicyNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event with name &apos;{0}&apos; is not a public member of publisher type &apos;{1}&apos;..
        /// </summary>
        internal static string PublicEventNotFound {
            get {
                return ResourceManager.GetString("PublicEventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource key {0} is already registered within provider..
        /// </summary>
        internal static string ResourceKeyAlreadyExists {
            get {
                return ResourceManager.GetString("ResourceKeyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource manager for the given key {0} does not exist..
        /// </summary>
        internal static string ResourceManagerDoesNotExist {
            get {
                return ResourceManager.GetString("ResourceManagerDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration section &apos;{0}&apos; was not found..
        /// </summary>
        internal static string SectionNotFound {
            get {
                return ResourceManager.GetString("SectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem occured while connecting to security service..
        /// </summary>
        internal static string SecurityServiceConnectionProblem {
            get {
                return ResourceManager.GetString("SecurityServiceConnectionProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong smtp address format: {0}.
        /// </summary>
        internal static string SmtpAddressWrongFormat {
            get {
                return ResourceManager.GetString("SmtpAddressWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong smtp address format: {0}.
        /// </summary>
        internal static string SmtpAddressWrongFormat1 {
            get {
                return ResourceManager.GetString("SmtpAddressWrongFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sending of mails failed..
        /// </summary>
        internal static string SmtpMassegeSendingFailed {
            get {
                return ResourceManager.GetString("SmtpMassegeSendingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event with name &apos;{0}&apos; could not be registered as a publication. Static events are not supported. .
        /// </summary>
        internal static string StaticEventNotSupported {
            get {
                return ResourceManager.GetString("StaticEventNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed strategy type does not implement IPermissionStrategy..
        /// </summary>
        internal static string StrategyTypeDoesNotImplementIPermissionStrategy {
            get {
                return ResourceManager.GetString("StrategyTypeDoesNotImplementIPermissionStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create a subscription for the &apos;{0}&apos; method defined in type &apos;{1}&apos; because it has an overload.
        /// </summary>
        internal static string SubscriptionDoesNotSupportMethodOverloads {
            get {
                return ResourceManager.GetString("SubscriptionDoesNotSupportMethodOverloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token has expired..
        /// </summary>
        internal static string TokenExpired {
            get {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is not valid..
        /// </summary>
        internal static string TokenNotValid {
            get {
                return ResourceManager.GetString("TokenNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration is trying to enable undefined category id. Please check the category defenition..
        /// </summary>
        internal static string UndefinedCategoryError {
            get {
                return ResourceManager.GetString("UndefinedCategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event broker initialized for non-WPF host application. User interface thread option unsupported in current configuration..
        /// </summary>
        internal static string UserInterfaceNotSupported {
            get {
                return ResourceManager.GetString("UserInterfaceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong configuration of FtpNotifier: the address is not correct ftp address..
        /// </summary>
        internal static string WrongFtpNotifierConfigurationAddress {
            get {
                return ResourceManager.GetString("WrongFtpNotifierConfigurationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong configuration of SmtpAddressedNotifier:  the recipient parameter is not correct e-mail address..
        /// </summary>
        internal static string WrongSmtpAddressedNotifierConfigurationRecipeintFormat {
            get {
                return ResourceManager.GetString("WrongSmtpAddressedNotifierConfigurationRecipeintFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong configuration of SmtpAddressedNotifier: the recipient parameters is required..
        /// </summary>
        internal static string WrongSmtpAddressedNotifierConfigurationRecipient {
            get {
                return ResourceManager.GetString("WrongSmtpAddressedNotifierConfigurationRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong configuration of SmtpNotifier: the port parameter is incorrect..
        /// </summary>
        internal static string WrongSmtpNotifierConfigurationPort {
            get {
                return ResourceManager.GetString("WrongSmtpNotifierConfigurationPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong configuration of SmtpNotifier: the sender and host parameters are required..
        /// </summary>
        internal static string WrongSmtpNotifierConfigurationRequired {
            get {
                return ResourceManager.GetString("WrongSmtpNotifierConfigurationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong configuration of SmtpNotifier: the sender parameter is not correct e-mail address. .
        /// </summary>
        internal static string WrongSmtpNotifierConfigurationSenderFormat {
            get {
                return ResourceManager.GetString("WrongSmtpNotifierConfigurationSenderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong configuration of SmtpNotfier: the ssl parameter has no correct value..
        /// </summary>
        internal static string WrongSmtpSslFormat {
            get {
                return ResourceManager.GetString("WrongSmtpSslFormat", resourceCulture);
            }
        }
    }
}
