//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-05 - 16.15.27
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace EFC.Sample.Auditing.Data.Contracts.Dto
{
    [DataContract()]
    public partial class DepartmentDataDto
    {
        [DataMember()]
        public Int32 Id { get; set; }

        [DataMember()]
        public String DepartmentName { get; set; }

        [DataMember()]
        public String Location { get; set; }

        [DataMember()]
        public List<EmployeeDepartmentMappingDto> EmployeeDepartmentMappings { get; set; }

        public DepartmentDataDto()
        {
        }

        public DepartmentDataDto(Int32 id, String departmentName, String location, List<EmployeeDepartmentMappingDto> employeeDepartmentMappings)
        {
			this.Id = id;
			this.DepartmentName = departmentName;
			this.Location = location;
			this.EmployeeDepartmentMappings = employeeDepartmentMappings;
        }
    }
}
