//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-03-05 - 16.15.28
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace EFC.Sample.Auditing.Data.Contracts.Dto
{
    [DataContract()]
    public partial class EmployeeDataDto
    {
        [DataMember()]
        public Int32 Id { get; set; }

        [DataMember()]
        public String FirstName { get; set; }

        [DataMember()]
        public String LastName { get; set; }

        [DataMember()]
        public DateTime DOB { get; set; }

        [DataMember()]
        public List<EmployeeDepartmentMappingDto> EmployeeDepartmentMappings { get; set; }

        public EmployeeDataDto()
        {
        }

        public EmployeeDataDto(Int32 id, String firstName, String lastName, DateTime dOB, List<EmployeeDepartmentMappingDto> employeeDepartmentMappings)
        {
			this.Id = id;
			this.FirstName = firstName;
			this.LastName = lastName;
			this.DOB = dOB;
			this.EmployeeDepartmentMappings = employeeDepartmentMappings;
        }
    }
}
