//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFC.Sample.Auditing.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentData
    {
        public DepartmentData()
        {
            this.EmployeeDepartmentMappings = new HashSet<EmployeeDepartmentMapping>();
        }
    
        public int Id { get; set; }
        public string DepartmentName { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<EmployeeDepartmentMapping> EmployeeDepartmentMappings { get; set; }
    }
}
