//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFC.Sample.Auditing.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDepartmentMapping
    {
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual DepartmentData DepartmentData { get; set; }
        public virtual EmployeeData EmployeeData { get; set; }
    }
}
