//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFC.Sample.Auditing.Services.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SampleContainer : DbContext
    {
        public SampleContainer()
            : base("name=SampleContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DepartmentData> DepartmentDatas { get; set; }
        public virtual DbSet<EmployeeData> EmployeeDatas { get; set; }
        public virtual DbSet<EmployeeDepartmentMapping> EmployeeDepartmentMappings { get; set; }
    }
}
