//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Experion.TTS.Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODULE
    {
        public int MODULE_ID { get; set; }
        public string MODULE_DESCR { get; set; }
        public string MAIN_MENU_CAPTION { get; set; }
        public string MENU_CAPTION { get; set; }
        public string MENU_TOOLTIP { get; set; }
        public string CALL_PROCEDURE { get; set; }
        public Nullable<int> FACE_ID { get; set; }
        public Nullable<int> MENU_ORDER { get; set; }
        public string START_MENU_GROUP { get; set; }
        public string ENABLE { get; set; }
        public string MODULE_INFO { get; set; }
        public Nullable<short> ACTION_EDIT { get; set; }
        public Nullable<short> ACTION_INSERT { get; set; }
        public Nullable<short> ACTION_DELETE { get; set; }
        public Nullable<short> ACTION_BANK_DETAILS_EDIT { get; set; }
        public Nullable<short> ACTION_SUN_IMPORT { get; set; }
    }
}
