//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Experion.TTS.Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ProjectMembers = new HashSet<ProjectMember>();
            this.Timesheets = new HashSet<Timesheet>();
        }
    
        public int ProjectId { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public byte Status { get; set; }
        public decimal EffortBudget { get; set; }
        public decimal CostBudget { get; set; }
        public int ProjectStatus { get; set; }
        public Nullable<bool> HideFromTimesheet { get; set; }
    
        public virtual ICollection<ProjectMember> ProjectMembers { get; set; }
        public virtual ProjectStatu ProjectStatu { get; set; }
        public virtual ICollection<Timesheet> Timesheets { get; set; }
    }
}
