//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Experion.TTS.Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStatu
    {
        public ProjectStatu()
        {
            this.Projects = new HashSet<Project>();
        }
    
        public int ProjectStatusId { get; set; }
        public string ProjectStatus { get; set; }
    
        public virtual ICollection<Project> Projects { get; set; }
    }
}
