//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Experion.TTS.Service.Model
{
    using System;
    using System.Collections.Generic;

    using EFC.Components.Data;

    public partial class Setting : IEntity<string>
    {
        public string KeyData { get; set; }
        public string ValueData { get; set; }

        public string Id { get
        {
            return KeyData;
        } }
    }
}
