//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Experion.TTS.Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheet
    {
        public long TimesheetId { get; set; }
        public int UserId { get; set; }
        public int ProjectId { get; set; }
        public int ActivityId { get; set; }
        public System.DateTime TimesheetDate { get; set; }
        public string Task { get; set; }
        public decimal Duration { get; set; }
        public string Remarks { get; set; }
        public string TicketID { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Project Project { get; set; }
        public virtual USER_DEFN USER_DEFN { get; set; }
    }
}
